-- crear la base de datos
DROP DATABASE IF EXISTS MUSICA_URBANA;
CREATE DATABASE MUSICA_URBANA;
USE MUSICA_URBANA;

CREATE TABLE IF NOT EXISTS usuarios (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(50) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    ROL ENUM('usuario', 'administrador') NOT NULL DEFAULT 'usuario',
);

-- tabla de artistas
CREATE TABLE IF NOT EXISTS ARTISTA (
    CODARTISTA INT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    BIOGRAFIA TEXT,
    FECHA_NACIMIENTO VARCHAR(255),
    PAIS_ORIGEN VARCHAR(100)
);

-- tabla de albumes
CREATE TABLE IF NOT EXISTS ALBUM (
    CODALBUM INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    FECHA_LANZAMIENTO DATE,
    CODARTISTA INT,
    CARATULA VARCHAR(255),
    FOREIGN KEY (CODARTISTA) REFERENCES ARTISTA(CODARTISTA)
);

-- tabla de canciones
CREATE TABLE IF NOT EXISTS CANCION (
    CODCANCION INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    DURACION TIME,
    CODALBUM INT,
    IMAGEN VARCHAR(255),
    FOREIGN KEY (CODALBUM) REFERENCES ALBUM(CODALBUM)
);