-- Crear la base de datos
DROP DATABASE IF EXISTS MUSICA_URBANA;
CREATE DATABASE MUSICA_URBANA;
USE MUSICA_URBANA;

CREATE TABLE IF NOT EXISTS USUARIOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(50) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    ROL ENUM('usuario', 'administrador') NOT NULL DEFAULT 'usuario',
    EMAIL VARCHAR(100) NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Artistas
CREATE TABLE IF NOT EXISTS ARTISTA (
    CODARTISTA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    BIOGRAFIA TEXT,
    FECHA_NACIMIENTO VARCHAR(255),
    PAIS_ORIGEN VARCHAR(100),
    IMAGEN varchar(255)
);

-- Tabla de Álbumes
CREATE TABLE IF NOT EXISTS ALBUM (
    CODALBUM INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    FECHA_LANZAMIENTO DATE,
    CODARTISTA INT,
    CARATULA VARCHAR(255),
    FOREIGN KEY (CODARTISTA) REFERENCES ARTISTA(CODARTISTA)
);

-- Tabla de Canciones
CREATE TABLE IF NOT EXISTS CANCION (
    CODCANCION INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    DURACION TIME,
    AUDIO VARCHAR(255),
    CODALBUM INT,
    IMAGEN VARCHAR(255),
    FOREIGN KEY (CODALBUM) REFERENCES ALBUM(CODALBUM)
);

-- Tabla de Comentarios
CREATE TABLE IF NOT EXISTS COMENTARIOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ID_ALBUM INT NOT NULL,
    COMENTARIO TEXT NOT NULL,
    FECHA_COMENTARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID),
    FOREIGN KEY (ID_ALBUM) REFERENCES ALBUM(CODALBUM)
);

ALTER TABLE COMENTARIOS ADD COLUMN LIKES INT DEFAULT 0;
ALTER TABLE COMENTARIOS ADD COLUMN DISLIKES INT DEFAULT 0;
